### ISSUE TITLE
Has Kraftwagen become super slow for anyone else?

### ISSUE THREAD

**Issue by bighappyface** [kraftwagen/kraftwagen#55]
Recently `kw-b` crawls for me. It seems to hang just after the Drupal download.

**Comment by rolfvandekrol** [comment]
Hey! `drush kw-b` is not slow for me. It also is not particularly fast, but 'good enough'. 

Maybe running `drush kw-b -v`could give you a bit more information which part is very slow. It also might help to remove your drush cache (`rm ~/.drush/cache`) so it can be rebuild.

**Comment by bighappyface** [comment]
I discovered that things speed up drastically once I remove various dev-related directories (e.g. node_modules for css/js development) from the src directory. Can directories be excluded from builds via kraftwagenrc.php?

**Comment by rolfvandekrol** [comment]
Ah, that explains. npm modules tend to include quite some files and the build process of kraftwagen simply copies those files from the `src` dir to `build/profiles/PROFILENAME`, so that can take a lot of time. I know people experimented with letting kraftwagen symlink the `src` dir to the profile, instead of copying it, but that those experiments were not very succesful (i.e. they ran into a lot of errors).

**Comment by bighappyface** [comment]
I worked out a way to speed things up by deferring installs until I have a built version of the site. Thanks!
